import torch
import torch.nn as nn
from torch.nn import functional as F
# read lines from data file
batch_size = 64
block_size = 256
max_iters = 5000
eval_interval = 500
learning_rate = 1e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2

torch.manual_seed(1337)

with open("/home/dev/gpt-shakespeare/data/input.txt",  "r", encoding="utf-8") as data:
    text= data.read()
    #print(text[:1000])

chars = sorted(list(set(text)))

vocab_size = len(chars)
#print(" ".join(chars))
#print(vocab_size)


#Create our mapping for tokenization

stoi = {ch: i for i,ch in enumerate(chars)} # iterate through all the chars and create a lookup table for the chars to the integers 

itoi = {i: ch for i,ch in enumerate(chars)} # Same thing but from the integers to the chars.

# Lambda functions are anoymous functions that can have any number of arguments but can only return on expression

encode = lambda s: [stoi[c] for c in s] # encoding a string, by translating all of the chars individually 

decode = lambda l: ''.join([itoi[i] for i in l]) # decode by translating the integers to chars and joining them together

#print(encode("hii there"))
#print(decode(encode("hii there")))

# tokenize the entire dataset using torch

data = torch.tensor(encode(text) , dtype=torch.long)
#print(data.shape, data.dtype)
#print(data[:1000])

'''
split into train and validation
'''

n = int(0.9 * len(data)) # gathering 90 percent of our data and using that as train_data
train_data = data[:n]
valid_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else valid_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) #generates random posotions of batch_size offsets of 4x8 tensor, gives 4 nums generated by len of data -block_size
    x = torch.stack([data[i:i+block_size] for i in ix])  # first block_size char starting at i
    y = torch.stack([data[i+1: i+block_size+1] for i in ix]) # similar but it is the next char hence i+1
    x , y = x.to(device), y.to(device)
    return x,y

# evaulate loss function, that gets the average between splits train and val
@torch.no_grad() # context manager tells pytorch that we will not use .backward on anything in the following function

def estimate_loss():
    out = {}
    model.eval() #eval 
    for split in ['train', 'valid']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits,loss = model(X,Y)
            losses[k] = loss.item()

        out[split] = losses.mean() #get average loss between the two splits
    model.train() #train mode
    return out

class Head(nn.Module):
    """One head of self-attention"""
    def __init__(self,head_size):
        super(). __init__()
        self.key = nn.Linear(n_embd, head_size, bias=False) # vector saying what do I contain
        self.query = nn.Linear(n_embd, head_size, bias=False) #vector that essentially is saying what am I looking for.
        # these make up our weights
        self.value = nn.Linear(n_embd, head_size, bias=False)# Later on when we are calculating our self-attention we use value to aggregate, because we don't want to use our raw x value
        #tril or lower-triangle part of a 2d matrix we use for self-attention
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size))) #[T,T]
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)
        q = self.query(x)
        #compute attention scores
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, hs) @ (B, hs, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,hs)
        out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out
    
class MultiHeadAttention(nn.Module):
    def __init__ (self, num_heads, head_size):
        super(). __init__()
        self.heads= nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(num_heads * head_size , n_embd)
        self.dropout = nn.Dropout(dropout)
    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out


class FeedForward(nn.Module):
    """Simple linear layer followed by a non-linearity"""
    def __init__ (self, n_embeds):
        super(). __init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )
    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    def __init__(self, n_embeds, n_head):
        super(). __init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))# added the x + for risidual connections, so we can fork off, do computations, and come back
        x = x + self.ffwd(self.ln2(x))
        return x



class BigramLanguageModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.token_embedding_table = nn.Embedding(vocab_size, n_embd) # create emebedding table that is 65x65
        self.position_embedding_table = nn.Embedding(block_size, n_embd) #also need idx positions going forward 
        #self.sa_head = Head(n_embeds) # create self_attention_head in our language model class
        #self.sa_heads = MultiHeadAttention(4, n_embd//4) #4 heads for 8-dimensional self_attention
        #self.ffwd = FeedForward(n_embeds)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm

        self.lm_head = nn.Linear(n_embd, vocab_size) #linear layer because our model is getting more complex, best practice

        self.apply(self._init_weights)
    
    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
            elif isinstance(module, nn.Embedding):
                torch.nn.init.normal_(module.weight, mean = 0.0, std=0.02)

    def forward(self, idx, targets=None):
        # logits are the raw outputs from the final layer of the deep learning model
        B, T = idx.shape
        tok_embed = self.token_embedding_table(idx) #batch by time by channel tensor or [64,8,65]
        pos_embed = self.position_embedding_table(torch.arange(T, device = device)) #[T,C] integers from 0 -> T-1
        x = tok_embed + pos_embed # [B,T,C]
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x) #[B,T,vocab_size]
        
        if targets == None: #if we have the targets we will get a loss value, else we will just get the logits
            loss = None
        else:   
            # reshape our logits tensor 
            B,T,C = logits.shape 
            logits = logits.view(B*T, C) #stretching out the array from 3d to 2d
            targets = targets.view(B*T) # targets is in the shape of B,T, now it is a vector 
            loss = F.cross_entropy(logits, targets) 
        return logits, loss # We are predicting what is coming next based off of the identity of a single tokens

    #generate function
    def generate(self,idx,max_new_tokens):
        #idx is an array [B,T] in our current context
        for _ in range(max_new_tokens):
            #get the predictions
            #crop idx to the last block_size
            idx_cond = idx[:, -block_size:] # because we use pos_embed, idx can never be larger than block_size, because we will run out of scope
            logits,loss = self(idx_cond)
            logits = logits[:, -1, :] #get the last step, convert to [B, C], we take out the T dimension, because they aren't predicitons for what comes next
            probs = F.softmax(logits, dim=-1) # convert to softmax, [0,1]
            idx_next = torch.multinomial(probs, num_samples=1) # [B,1] for each batch dimension, we will get a single prediction for what comes next.
            idx = torch.cat((idx, idx_next), dim=1) # append sample index or integers to the running dimension, [B, T+1]
        return idx
    

#xb, yb = get_batch('train')

model = BigramLanguageModel()
m = model.to(device)
# for smaller nerual networks we can get away with much higher learning rates if we use AdamW compared to SGD
#optimizer = torch.optim.AdamW(m.parameters(), lr=learning_rate) #AdamW is a much more complex optimizer, it customizes each parameter's learning rate based on its graident history
print(sum(p.numel() for p in m.parameters())/ 1e6, 'M parameters')
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

def training_loop(batch_size: int):
    for iter in range(max_iters):
        if iter % eval_intervals == 0 or iter == max_iters -1:
            losses = estimate_loss()
            print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['valid']:.4f}")
        xb,yb = get_batch('train')
        logits, loss = model(xb,yb)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
    context = torch.zeros((1, 1), dtype=torch.long, device=device)
    print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))
    open('more.txt', 'w').write(decode(m.generate(context, max_new_tokens=10000)[0].tolist()))

# calling our training loop with a batch size of 32

#training_loop(batch_size=batch_size)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['valid']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))
open('more.txt', 'w').write(decode(m.generate(context, max_new_tokens=10000)[0].tolist()))